name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress comando line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.10.0-chrome-121.0.6167.85-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.1

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comand: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: c8f13821-6a35-473f-b909-f8b8bf1047b6
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome: 
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.10.0-chrome-121.0.6167.85-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.1

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comand: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: c8f13821-6a35-473f-b909-f8b8bf1047b6
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.10.0-chrome-121.0.6167.85-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get Code
        uses: actions/checkout@v4.1.1

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-comand: npm install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: c8f13821-6a35-473f-b909-f8b8bf1047b6
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
